package defaults

import (
	"github.com/chri5bot/reviews-pya/models"
)

// Reviews default reviews
var Reviews = []models.Review{
	models.Review{
		ID:         Review1,
		UserID:     User1,
		StoreID:    Store1,
		PurchaseID: Purchase1,
		Score:      5,
		Opinion:    "Esta bien",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review2,
		UserID:     User2,
		StoreID:    Store2,
		PurchaseID: Purchase2,
		Score:      1,
		Opinion:    "Esta mal",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review3,
		UserID:     User2,
		StoreID:    Store2,
		PurchaseID: Purchase3,
		Score:      3,
		Opinion:    "Estuvo agradable",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review4,
		UserID:     User1,
		StoreID:    Store1,
		PurchaseID: Purchase4,
		Score:      2,
		Opinion:    "Demoro demasiado",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review5,
		UserID:     User2,
		StoreID:    Store2,
		PurchaseID: Purchase5,
		Score:      4,
		Opinion:    "Estuvo bastante bien",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review6,
		UserID:     User2,
		StoreID:    Store2,
		PurchaseID: Purchase6,
		Score:      4,
		Opinion:    "Recomiendo este lugar",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review7,
		UserID:     User1,
		StoreID:    Store1,
		PurchaseID: Purchase7,
		Score:      1,
		Opinion:    "La comida llego fria",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review8,
		UserID:     User2,
		StoreID:    Store1,
		PurchaseID: Purchase8,
		Score:      2,
		Opinion:    "No fue lo que pedi",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review9,
		UserID:     User1,
		StoreID:    Store2,
		PurchaseID: Purchase9,
		Score:      1,
		Opinion:    "Esta mal",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
	models.Review{
		ID:         Review10,
		UserID:     User2,
		StoreID:    Store1,
		PurchaseID: Purchase10,
		Score:      5,
		Opinion:    "Estuvo excelente",
		CreatedAt:  Date,
		UpdatedAt:  Date,
	},
}
